blockQueue:main.cc
	g++ -o $@ $^ -std=c++11
# main.o:main.cc
# 	g++ -c -o $@ $<
# # BlockQueue.o:BlockQueue.hpp
# 	g++ -c -o $@ $<
.PHONY:clean
clean:
	rm -f blockQueue
.PHONY:run
run:
	@./blockQueue

